---
title: "Group 4 Project"
author: "Laura Larregui, Angela Garcia, John Christman"
date: "11/18/2019"
output:
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r readWines}
readURL <- function(inputURL)  #Begin function named readURL that takes a URL
{
  csvFile <- read.csv(url(inputURL), sep = ';')  #assign the results of the URL call as a csv file to a dataframe named csvFile. Added sep = ';' to seperate the data into columns
  return(csvFile)  # return the dataframe
}

redWine <- readURL("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv")
whiteWine <- readURL("https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-white.csv")

str(redWine)
str(whiteWine)
summary(redWine)
summary(whiteWine)


```
```{r cleanWine}
#THe datasets only have one column of data.  The column names are separated by periods the data by semi-colons
#1. Create columns 
#2.  separate the data into the columns
#3.  Verify no NAs
redWine <- na.omit(redWine)
whiteWine<-na.omit (whiteWine)

```

```{r visualizeWine }
#1.  Create visulaizations for the data
#heat maps, histograms and scatter plots?

#Heatmaps
red_cor <- cor(redWine)
white_cor <- cor(whiteWine)
col<- colorRampPalette(c("blue", "white", "red"))(20)
heatmap(x = red_cor, col = col, symm = TRUE)
heatmap(x = white_cor, col = col, symm = TRUE)

#Histograms
hist(redWine$quality)
hist(whiteWine$quality)

library(grid)
library(gridExtra)
library (ggplot2)
h1 <- ggplot(aes(density), data = redWine) + geom_histogram(bins = 30) 

h2 <- ggplot(aes(alcohol), data = redWine) + geom_histogram(bins = 30)

h3 <- ggplot(aes(quality), data = redWine) + geom_histogram(bins = 7)


grid.arrange(h1,h2,h3,ncol=2)

```

```{r correlationWine}
#1. Create the correlation matrix

#Red Wine Correlation Matrix

#install.packages("corrplot")
library(corrplot)
red_cor <- cor(redWine)
round(red_cor, 2)
corrplot(red_cor, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)
#Positive correlations are displayed in blue and negative correlations in red color. Color intensity and the size of the circle are proportional to the correlation coefficients.

#Correlation matrix with numbers
corrplot(red_cor, method = 'number', type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)

#White Wine Correlation Matrix

#install.packages("corrplot")
library(corrplot)
white_cor <- cor(whiteWine)
round(white_cor, 2)
corrplot(white_cor, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)
#Correlation matrix with numbers
corrplot(white_cor, method = 'number',type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)
##Reference: http://www.sthda.com/english/wiki/correlation-matrix-a-quick-start-guide-to-analyze-format-and-visualize-a-correlation-matrix-using-r-software
```

```{r learingWine}
#Machine learning techniques to see if we can train the system to pick a good wine
```


